[package]
name = "nuxi-cached-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nuxi-cached"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
