[package]
name = "nuxicachedcli"
version = "0.1.2"
edition = "2021"
include = ["src/**/*"]

[[bin]]
name = "nuxi-cached"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.7"
