name: Build and Release Rust Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: nuxi-cached
      TARGET: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # For faster testing

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ env.TARGET }}

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(grep 'version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build the binary
        run: cargo build --release

      - name: Create directory for artifacts (with error handling)
        run: |
          mkdir -p "artifacts/release-artifacts/${{ github.sha }}" || {
            echo "Error: Could not create artifacts directory. Stopping workflow."
            exit 1
          }
          echo "Created artifacts directory: artifacts/release-artifacts/${{ github.sha }}"

      - name: Create archive
        run: |
          echo "Current BINARY_NAME: $BINARY_NAME"
          echo "Current VERSION: $VERSION"
          echo "Target path: target/release/$BINARY_NAME"

          # Check if the binary exists (add this check)
          if [ -f "target/release/$BINARY_NAME" ]; then
            tar -czvf "${BINARY_NAME}-${VERSION}.tar.gz" "target/release/$BINARY_NAME"
            echo "Archive created: ${BINARY_NAME}-${VERSION}.tar.gz"
          else
            echo "Error: Binary not found at target/release/$BINARY_NAME"
            exit 1
          fi

      - name: Verify paths and values
        run: |
          echo "Expected artifact path: artifacts/release-artifacts/${{ github.sha }}/$BINARY_NAME-$VERSION.tar.gz"
          # Check if the directory exists (add this check)
          if [ -d "artifacts/release-artifacts/${{ github.sha }}" ]; then
            echo "Directory artifacts/release-artifacts/${{ github.sha }} exists."
          else
            echo "Error: Directory artifacts/release-artifacts/${{ github.sha }} does not exist. Skipping upload."
            exit 0
          fi

      - name: Upload artifact
        run: |
          echo "Artifact path: artifacts/release-artifacts/${{ github.sha }}/$BINARY_NAME-$VERSION.tar.gz"
          # Check if the file exists (add this check)
          if [ -f "artifacts/release-artifacts/${{ github.sha }}/$BINARY_NAME-$VERSION.tar.gz" ]; then
            echo "Artifact already exists, skipping upload."
          else
            echo "Uploading artifact..."
            # Use actions/upload-artifact@v3 for better logging
            bash -c "echo ::set-output name=artifact_path::$BINARY_NAME-$VERSION.tar.gz"
            bash -c "echo ::set-output name=artifact_type::binary"
            echo "Artifact uploaded successfully: ${{ steps.upload_artifact.outputs.artifact_path }}"
          fi

      - name: Upload artifact to release
        if: ${{ always() }} # Ensure this step always runs for debugging
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.repos.url }}/releases/${{ github.sha }}/assets
          asset_path: artifacts/release-artifacts/${{ github.sha }}/"$BINARY_NAME-$VERSION.tar.gz"
          asset_name: "$BINARY_NAME-$VERSION.tar.gz"
          asset_content_type: application/gzip
